### ISSUE TITLE
デザインについて

### ISSUE THREAD

**Issue by d-junk** [uchibori-mdnt/Clinic-HP#14]
個人の主観になりますのであくまでも参考程度にお願いします。
・グローバルメニューのアクセスとお問い合わせボタンの間に区切り線がある方がボタンの範囲が分かってよい
・グローバルメニューの外来〜採用情報のリンクの範囲が上下は余裕があるが、左右が余裕がないので上下左右に余裕があった方がよい
・タブレット〜スマホあたりのウィンドウサイズのコンテンツ幅が狭い
・スマホ表示時のコンテンツ幅の左右の余白をもう少し少なくしたほうが、文字量もたくさん入ってよいのでは
・スマホ表示時の文字サイズが少し小さい
・病院概要のテーブルの上下の余白のバランスが悪い

**Comment by uchibori-mdnt** [comment]
✔・グローバルメニューの外来〜採用情報のリンクの範囲が上下は余裕があるが、左右が余裕がないので上下左右に余裕があった方がよい
✔・タブレット〜スマホあたりのウィンドウサイズのコンテンツ幅が狭い
✔・スマホ表示時のコンテンツ幅の左右の余白をもう少し少なくしたほうが、文字量もたくさん入ってよいのでは
・スマホ表示時の文字サイズが少し小さい
✔・病院概要のテーブルの上下の余白のバランスが悪い
