### ISSUE TITLE
デザイン崩れ

### ISSUE THREAD

**Issue by d-junk** [uchibori-mdnt/Clinic-HP#16]
トップページ
https://main--vermillion-speculoos-7f4266.netlify.app/
- 大きいディスプレイだとキャッチ画像が横幅いっぱいに表示されない

下層ページ全般
- ブラウザの開発者コンソールでエラーが複数出ている

外来
https://main--vermillion-speculoos-7f4266.netlify.app/outpatient
- 電話番号がiPhoneで閲覧した際にリンクの色が白色となり見づらい
- HTMLにclassをつけているが、CSS側で使用していないものがある。CSSやJSで使わないならclassは増やさない
- 見出しの上下の余白のバランスが良くないため、上のコンテンツなのか下のコンテンツに関係しているのか分かりづらい。
- 再診の方へ＜受診の流れ＜受付が２カラムになっているが左右の余白が揃っていない

診療科
https://main--vermillion-speculoos-7f4266.netlify.app/subjects
- Moreボタンの丸いアイコンが横に潰れて表示されている

アクセス
https://main--vermillion-speculoos-7f4266.netlify.app/access
- 交通手段の左右のカラムが上下にずれている
- 駐車場のテーブル内で複数行の場合の余白がせまい

お問い合わせ
https://main--vermillion-speculoos-7f4266.netlify.app/inquiry
- 電話番号がiPhoneで閲覧した際にリンクの色が白色となり見づらい

**Comment by uchibori-mdnt** [comment]
- [x] お問い合わせフォーム入れる（採用ページ）
- [x] 採用タイトル一覧を上部に設置する
- [x] お知らせ詳細からrecruit.htmlにとばして、一致するidがあればそこに遷移させるというコードを書く

- [x] 大きいディスプレイだとキャッチ画像が横幅いっぱいに表示されない
- [x] 下層ページ全般（ブラウザの開発者コンソールでエラーが複数出ている）
  　 └ 採用ページのエラーのみ残っている。Newt変更のため変更時修正
- [x] 採用ページNewt修正
- [x] 電話番号がiPhoneで閲覧した際にリンクの色が白色となり見づらい
- [x] HTMLにclassをつけているが、CSS側で使用していないものがある。CSSやJSで使わないならclassは増やさない
- [x] 見出しの上下の余白のバランスが良くないため、上のコンテンツなのか下のコンテンツに関係しているのか分かりづらい。
- [x] 再診の方へ＜受診の流れ＜受付が２カラムになっているが左右の余白が揃っていない
- [x] Moreボタンの丸いアイコンが横に潰れて表示されている
- [x] 交通手段の左右のカラムが上下にずれている
- [x] 駐車場のテーブル内で複数行の場合の余白がせまい
- [x] 電話番号がiPhoneで閲覧した際にリンクの色が白色となり見づらい
